### ISSUE TITLE
Regional Bird day :D

### ISSUE THREAD

**Issue by Zorcario14** [gr33nd3v1l/PKDB#10]
Could you maybe do a regional bird day? Where yo do giveaways on final evos of Regional Birds (Pidgeot, Noctowl, Swellow, Staraptor, Unfezant, Talonflame, Toucannon) It would be pretty cool; maybe even throw in Fearow? :P

**Comment by gr33nd3v1l** [comment]
Sure if you can think of sets and about 10-20 birds that would be included we'll get it on schedule

**Comment by Zorcario14** [comment]
Bird Jesus
Pidgeot(M) @ Level Ball
Ability: Big Pecks
EVs: 4 Def / 252 SpA / 252 Spe
Timid Nature
Ball: Level Ball
- Hurricane
- Heat Wave
- Roost
- U-turn

**Comment by Zorcario14** [comment]
Triple Threat
Dodrio(F) @ Level Ball
Ability: Early Bird
EVs: 252 Atk / 4 Def / 252 Spe
Ball: Level Ball
Jolly Nature
- Brave Bird
- Return
- Knock Off
- Pursuit

**Comment by Zorcario14** [comment]
Cyclonus
Fearow (M)@ Beast Ball
Ability: Sniper
EVs: 252 Atk / 4 SpD / 252 Spe
Jolly Nature
Ball: Beast Ball
- Drill Peck
- Double-Edge
- Drill Run
- U-turn

**Comment by Zorcario14** [comment]
Zephyr
Xatu (F) @ Friend Ball
Ability: Magic Bounce
EVs: 252 HP / 240 Def / 16 Spe
Timid Nature
Ball: Friend Ball
- Calm Mind
- Roost
- Psyshock
- Heat Wave

**Comment by Zorcario14** [comment]
Iron Fenix
Skarmory (F)@ Beast Ball
Ability: Sturdy
EVs: 252 HP / 4 Def / 252 SpD
Careful Nature
- Spikes
- Roost
- Iron Head
- Whirlwind

**Comment by Zorcario14** [comment]
Minerva
Noctowl (F) @ Moon Ball
Ability: Insomnia
EVs: 248 HP / 8 Def / 252 SpD
Calm Nature
Ball: Moon Ball
- Roost
- Defog
- Psycho Shift
- Night Shade

**Comment by Zorcario14** [comment]
Mistral
Swellow (F) @ Fast Ball
Ability: Scrappy
EVs: 4 Def / 252 SpA / 252 Spe
Timid Nature
Ball: Dream Ball
- Boomburst
- Heat Wave
- U-turn
- Sleep Talk

**Comment by Zorcario14** [comment]
Estrella
Staraptor (F) @ Fast Ball
Ability: Reckless
EVs: 252 Atk / 4 Def / 252 Spe
Ball: Fast Ball
Adamant Nature
- Brave Bird
- Double-Edge
- Final Gambit
- U-turn

**Comment by Zorcario14** [comment]
Hernandez
Honchkrow (M) @ Love Ball
Ability: Moxie
EVs: 252 Atk / 4 SpD / 252 Spe
Adamant Nature
- Brave Bird
- Sucker Punch
- Pursuit
- Superpower

**Comment by Zorcario14** [comment]
Harto
Unfezant (F) @ Love Ball
Ability: Super Luck
EVs: 252 Atk / 4 Def / 252 Spe
Adamant Nature
- Tailwind
- Hypnosis
- U-turn
- Aerial Ace

**Comment by Zorcario14** [comment]
Toucannon @ Leftovers
Ability: Skill Link
Adamant Nature
EVs: 252 HP/ 252 Atk/4 Speed
Beak Blast
Rock Blast/Bullet Seed/Brave Bird
Bullet Seed/U-turn/Swords Dance/Brick Break
Roost

**Comment by Zorcario14** [comment]
ANGRY BIRD
Toucannon (M) @ Lure Ball
Ability: Skill Link
Adamant Nature
EVs: 252 HP/ 252 Atk/4 Speed
- Beak Blast
- Rock Blast
- Bullet Seed
- Roost

**Comment by Zorcario14** [comment]
NERFED BIRD
Talonflame (F) @ Lure Ball
Ability: Gale Wings
EVs: 252 Atk / 4 Def / 252 Spe
Jolly Nature
Ball: Fast Ball
- Brave Bird
- Flare Blitz
- Swords Dance
- Roost

**Comment by Zorcario14** [comment]
Tiamat
Swanna (F) @ Heavy Ball
Ability: Hydration
EVs: 252 SpA / 4 SpD / 252 Spe
Timid Nature
- Hurricane
- Scald
- Defog
- Roost

**Comment by Zorcario14** [comment]
Liberty
Braviary @ Heavy Ball
Ability: Defiant
EVs: 252 HP / 168 SpD / 88 Spe
Careful Nature
Ball: Heavy Ball
- Substitute
- Bulk Up
- Brave Bird
- Roost

**Comment by Zorcario14** [comment]
Scavenger
Mandibuzz @ Friend Ball
Ability: Overcoat
EVs: 248 HP / 136 Def / 108 SpD / 16 Spe
Bold Nature
Ball: Moon Ball
- Foul Play
- Roost
- Taunt
- Defog

**Comment by Zorcario14** [comment]
15 Birdzzz is that enough

**Comment by gr33nd3v1l** [comment]
15 Birds is enough but with the amount of catching up we have to do lately, we'll have to save this until you redeem, or next week if we get a free day

**Comment by Zorcario14** [comment]
If the birds in the balls can't be Legit, just put them in Dream Ballz or have them met as egg/from Johto
