### ISSUE TITLE
Custom Day(MasterAndy69)

### ISSUE THREAD

**Issue by MasterAndy69** [gr33nd3v1l/PKDB#16]
Sawsbuck( Spring Form) @ Gold Bottle Cap
Nature: Jolly
Ability: Sap Sipper
Level: 100
IV's: 31 ALL
EV's: 252 Atk/ 4 SpD/ 252 Spe
Move 1: Swords Dance
Move 2: Double-Edge
Move 3: Jump Kick
Move 4: Giga Drain

Sawsbuck( Autumn Form) @ Ability Capsule
Nature: Jolly
Ability: Sap Sipper
Level: 100
IV's: 31 ALL
EV's: 252 Atk/ 4 SpD/ 252 Spe
Move 1: Swords Dance
Move 2: Double-Edge
Move 3: Jump Kick
Move 4: Giga Drain

Sawsbuck( Summer Form) @ PP Max
Nature: Jolly
Ability: Sap Sipper
Level: 100
IV's: 31 ALL
EV's: 252 Atk/ 4 SpD/ 252 Spe
Move 1: Swords Dance
Move 2: Double-Edge
Move 3: Jump Kick
Move 4: Giga Drain

Sawsbuck( Winter Form) @ Lucky Egg
Nature: Jolly
Ability: Sap Sipper
Level: 100
IV's: 31 ALL
EV's: 252 Atk/ 4 SpD/ 252 Spe
Move 1: Swords Dance
Move 2: Double-Edge
Move 3: Jump Kick
Move 4: Giga Drain

Golrurk @ Choice Band
Nature: Adamant
Ability: Iron Fist
Level: 100
IV's: 31 ALL
EV's: 4 HP/ 252 Atk/ 252 Spe
Move 1: Stealth Rock
Move 2: Dynamic Punch
Move 3: Shadow Punch
Move 4: Ice Punch

Forretress @ Leftovers
Nature: Relaxed
Ability: Sturdy
Level: 100
IV's: 31 ALL
EV's: 252HP/ 252 Def/ 4 SpD
Move 1: Spikes
Move 2: Rapid Spin
Move 3: Volt Switch
Move 4: Gyro Ball

Scrafty @ Life Orb
Nature: Jolly
Ability: Moxie
Level: 100
IV's: 31 ALL
EV's: 4 HP/ 252 Atk/ 252 Spe
Move 1: Dragon Dance
Move 2: High Jump Kick
Move 3: Knock Off
Move 4: Iron Head

Purugly @ Focus Sash
Gender: Female( For attract)
Nature: Jolly
Ability: Defiant
Level: 100
IV's: 31 ALL
EV's: 252 Atk/ 4 Def/ 252 Spe
Move 1: Attract
Move 2: Protect
Move 3: Super Fang
Move 4:Fake Out

Sawk @ Expert Belt
Nature: Jolly
Ability: Mold Breaker
Level: 100
IV's: 31 ALL
EV's: 252 Atk/ 4 Def/ 252 Spe
Move 1: Close Combat
Move 2: Knock Off
Move 3: Poison Jab
Move 4: Zen Headbutt

Throh @ Heavy Ball
Nature: Careful
Ability: Guts
Level: 100
IV's: 31 ALL
EV's: 252 HP/ 4 Def/ 252 SpD
Move 1: Circle Throw
Move 2: Rest 
Move 3: Sleep Talk
Move 4: Bulk Up

Heliolisk @ Magnet
Nature: Timid
Ability: Dry Skin
Level: 100
IV's: 31 ALL
EV's: 252 SpA/ 4 SpD/ 252 Spe
Move 1: Volt Switch
Move 2: Hypervoice
Move 3: Signal Beam
Move 4: Thunderbolt

Legandaries:

Zapdos, Articuno, Moltres

Suicune, Entei, Raikou

Mespririt, Uxie, Azelf

**Comment by gr33nd3v1l** [comment]
Successfully completed!
