### ISSUE TITLE
Avalugg, Mandibuzz, Porygon2

### ISSUE THREAD

**Issue by boogknight** [gr33nd3v1l/PKDB#18]
Avalugg @ Leftovers
Ability: Sturdy
EVs: 248 HP / 8 Def / 252 SpD
Careful Nature
- Rapid Spin
- Recover
- Avalanche
- Roar
-------------------------------------------------------------------------------------------------------------------

Mandibuzz (F) @ Misty Seed
IVs: 0 Atk
EVs: 252 HP / 52 Def / 180 SpD / 20 Spe
Ability: Overcoat
Level: 100
Shiny: Yes
Calm Nature
- Foul Play
- Tailwind
- Toxic
- Roost
- Taunt _rl_
-----------------------------------------------------------------------------------------------------------------
Porygon2 @ Eviolite
Ability: Download
EVs: 252 HP / 252 SpA / 4 SpD
Quiet Nature
- Trick Room
- Recover
- Thunderbolt
- Ice Beam

**Comment by gr33nd3v1l** [comment]
Added today
