### ISSUE TITLE
Idea for a cool mon :)

### ISSUE THREAD

**Issue by GuillaumeMulier** [gr33nd3v1l/PKDB#23]
It would be awesome to add the star of film 15.
My idea is Keldeo-resolute not shiny, Ability : Justified, Nature Timid, lvl 100
His object is Choice Specs.
IV : 31/1/31/30/31/31
EV : 252SpAtt/4SpDef/252Spe
Moves : Hydropump + Scalp + Secret sword + Hidden Power (Electric)

This guy is the main character from the film where he beated kyurem. And in game it's the same it's a great wallbreaker that will destroy most of the switch in your opponent can do!

**Comment by gr33nd3v1l** [comment]
Definitely a cool idea, unfortunately it can't go over GTS :(
