### ISSUE TITLE
VGC team

### ISSUE THREAD

**Issue by anhphung97** [gr33nd3v1l/PKDB#24]
Hi, I want to suggest this VGC team by Shoma Honami and Gavin Michaels (two champions for two recent competitions). Thanks a lot!

# **EDIT: PLEASE NOTE ALL POKEMON ARE IN FACT LEVEL 100**

Shoma's team:

Pheromosa @ Focus Sash
Ability: Beast Boost
Level: 50
EVs: 252 Atk / 4 SpA / 252 Spe
Naughty Nature
- Ice Beam
- U-turn
- High Jump Kick
- Poison Jab

Tapu Lele @ Choice Specs
Ability: Psychic Surge
Level: 50
EVs: 236 HP / 212 Def / 36 SpA / 4 SpD / 20 Spe
Modest Nature
IVs: 0 Atk
- Moonblast
- Psychic
- Dazzling Gleam
- Thunderbolt

Garchomp @ Groundium Z -> Choice Scarf
Ability: Rough Skin
Level: 50
EVs: 188 HP / 236 Atk / 4 Def / 44 SpD / 36 Spe
Adamant Nature
IVs: 3 SpA
- Protect
- Earthquake
- Rock Slide
- Swords Dance

Gyarados @ Sitrus Berry
Ability: Intimidate
Level: 50
EVs: 68 HP / 252 Atk / 4 Def / 4 SpD / 180 Spe
Jolly Nature
- Protect
- Waterfall
- Earthquake
- Dragon Dance

Drifblim @ Psychic Seed
Ability: Unburden
Level: 50
EVs: 4 HP / 132 Def / 204 SpA / 4 SpD / 164 Spe
Timid Nature
IVs: 0 Atk
- Will-O-Wisp
- Shadow Ball
- Tailwind
- Rain Dance

Magnezone @ Electrium Z -> Choice Specs
Ability: Sturdy
Level: 50
EVs: 92 HP / 4 Def / 156 SpA / 4 SpD / 252 Spe
Modest Nature
IVs: 0 Atk
- Protect
- Thunderbolt
- Flash Cannon
- Magnet Rise

Gavin's team:

Magnezone @ Choice Specs  
Ability: Sturdy  
Level: 50  
EVs: 252 HP / 252 SpA / 4 SpD  
Modest Nature  
IVs: 0 Atk / 30 Spe  
- Thunderbolt  
- Flash Cannon  
- Volt Switch  
- Hidden Power [Ground]  
 
Araquanid @ Waterium Z  -> Leftovers
Ability: Water Bubble  
Level: 50  
EVs: 252 HP / 252 Atk / 4 SpD  
Brave Nature  
IVs: 0 Spe  
- Liquidation  
- Lunge  
- Substitute  
- Protect  
 
Porygon2 @ Eviolite  
Ability: Download  
Level: 50  
EVs: 252 HP / 252 Def / 4 SpA  
Bold Nature  
IVs: 0 Atk / 0 Spe  
- Ice Beam  
- Thunderbolt  
- Recover  
- Trick Room  
 
Hariyama @ Flame Orb  
Ability: Guts  
Level: 50  
EVs: 92 HP / 252 Atk / 164 Def  
Brave Nature  
IVs: 0 Spe  
- Fake Out  
- Close Combat  
- Knock Off  
- Feint  
 
Snorlax @ Figy Berry  
Ability: Gluttony  
Level: 50  
EVs: 68 HP / 252 Atk / 188 Def  
Brave Nature  
IVs: 2 Spe  
- Return  
- High Horsepower  
- Belly Drum  
- Protect  
 
Mimikyu @ Ghostium Z  -> Life Orb
Ability: Disguise  
Level: 50  
EVs: 4 HP / 252 Atk / 252 Spe  
Jolly Nature  
- Shadow Claw  
- Destiny Bond  
- Taunt  
- Trick Room

**Comment by EsmeeInWonderland** [comment]
I love it <3

**Comment by gr33nd3v1l** [comment]
GAVIN team will be on Trubbish

SHOMA team will be on Nosepass
