### ISSUE TITLE
MEGAEVOLUTION POKEMON

### ISSUE THREAD

**Issue by Daviduxtor** [gr33nd3v1l/PKDB#25]
It would be cool one day with all the pokemon with megaevolution

**Comment by gr33nd3v1l** [comment]
As usual, think of some sets and we can add it when we have a free day!

**Comment by Daviduxtor** [comment]
Do u have any pokemon done like from other streams?

**Comment by Daviduxtor** [comment]
Also is it possible to have a blaziken with thunder punch? Because a friend got it but i think its illegal

**Comment by herbsalami** [comment]
Ok this is one for Lucario: 

Lucario @ Lucarionite
Ability: Justified
EVs: 252 Atk / 4 Def / 252 Spe
Jolly Nature
- Ice Punch
- Close Combat
- Bullet Punch
- Iron Tail

**Comment by herbsalami** [comment]
Kangaskhan @ Kangaskhanite
Ability: Scrappy
EVs: 252 Atk / 4 SpD / 252 Spe
Jolly Nature
- Power-Up Punch
- Double-Edge
- Earthquake
- Sucker Punch

**Comment by herbsalami** [comment]
Charizard @ Charizardite X
Ability: Blaze
EVs: 252 Atk / 4 Def / 252 Spe
Jolly Nature
- Dragon Dance
- Flare Blitz
- Outrage
- Thunder Punch

**Comment by herbsalami** [comment]
Gengar @ Gengarite
Ability: Cursed Body
EVs: 4 Def / 252 SpA / 252 Spe
Timid Nature
- Taunt
- Destiny Bond
- Focus Blast
- Sludge Wave

**Comment by herbsalami** [comment]
Pinsir @ Pinsirite
Ability: Hyper Cutter
EVs: 252 Atk / 4 SpD / 252 Spe
Jolly Nature
- Swords Dance
- Return
- Quick Attack
- Close Combat

**Comment by herbsalami** [comment]
Sableye @ Sablenite
Ability: Prankster
EVs: 248 HP / 116 Def / 144 SpD
Careful Nature
- Fake Out
- Knock Off
- Will-O-Wisp
- Recover

**Comment by herbsalami** [comment]
Slowbro @ Slowbronite
Ability: Regenerator
EVs: 252 HP / 252 Def / 4 SpD
Bold Nature
- Toxic
- Slack Off
- Ice Beam
- Iron Defense

**Comment by herbsalami** [comment]
Venusaur @ Venusaurite
Ability: Chlorophyll
EVs: 232 HP / 180 Def / 80 SpD / 16 Spe
Bold Nature
- Giga Drain
- Knock Off
- Synthesis
- Hidden Power Fire

**Comment by anhphung97** [comment]
Scizor @ Scizorite  ~~> Gold Bottle Cap
Ability: Light Metal
EVs: 248 HP / 116 Def / 128 SpD / 16 Spe
Impish Nature
- Swords Dance
- Roost
- Bullet Punch
- U-turn

**Comment by anhphung97** [comment]
Gyarados @ Gyaradosite ~~> Gold Bottle Cap
Ability: Intimidate
EVs: 252 Atk / 4 Def / 252 Spe
Jolly Nature
- Dragon Dance
- Crunch
- Waterfall
- Substitute

**Comment by anhphung97** [comment]
Charizard @ Charizardite Y ~~> Gold Bottle Cap
Ability: Blaze
EVs: 4 Def / 252 SpA / 252 Spe
Timid Nature
- Fire Blast
- Solar Beam
- Focus Blast
- Roost

**Comment by anhphung97** [comment]
Alakazam @ Alakazite ~~> Gold Bottle Cap
Ability: Magic Guard
EVs: 4 Def / 252 SpA / 252 Spe
Timid Nature
- Psychic
- Shadow Ball
- Focus Blast
- Substitute

**Comment by anhphung97** [comment]
Mawile @ Mawilite ~~> Gold Bottle Cap
Ability: Hyper Cutter
EVs: 92 HP / 252 Atk / 164 Spe
Adamant Nature
- Play Rough
- Sucker Punch
- Thunder Punch
- Fire Fang

**Comment by anhphung97** [comment]
Aerodactyl @ Aerodactylite ~~> Gold Bottle Cap
Ability: Unnerve
EVs: 252 Atk / 4 SpD / 252 Spe
Jolly Nature
- Stone Edge
- Wing Attack
- Earthquake
- Pursuit

**Comment by anhphung97** [comment]
Sharpedo @ Sharpedonite ~~> Gold Bottle Cap
Ability: Speed Boost
EVs: 252 Atk / 4 SpD / 252 Spe
Adamant Nature
- Protect
- Crunch
- Waterfall
- Psychic Fangs
