### ISSUE TITLE
[TYPE: Fighting] Day

### ISSUE THREAD

**Issue by Daviduxtor** [gr33nd3v1l/PKDB#7]
Do a fighting type giveaway add Breelom or Pangoro or Hawlucha or Machamp add like 6 mons more or less but just fighting type. If u want obviously :)

**Comment by gr33nd3v1l** [comment]
Sounds good, added to project list

Think of some sets

**Comment by Daviduxtor** [comment]
Dude one poke that should be is heracross is my favorite pokemon of fighting type

**Comment by Daviduxtor** [comment]
Heracross (M) @ Choice Scarf
Trait: Earthquake Spiral
EVs: 4 HP / 252 Atk / 252 Spd
Jolly Nature (+Spd, -SAtk)
- Close Combat
- Earthquake
- Stone Edge
- Megahorn

_will add - make it event_

**Comment by Daviduxtor** [comment]
Pangoro @ Choice Scarf
Ability: Mold Breaker
EVs: 252 Atk, 252 Speed, 4 HP
Nature: Jolly
-Earthquake
-Crunch
-Sky Uppercut/ Brick Break
-Stone Edge/ Poison Jab

**Comment by Daviduxtor** [comment]
Breloom (M) @ Life Orb
Trait: Technician
EVs: 252 HP / 252 Atk / 4 Def
Adamant Nature (+Atk, -SAtk)
-Mach Punch
-Bullet Seed
-Spore
-Sword's Dance

**Comment by Daviduxtor** [comment]
Bewear @ Assault Vest

Adamant - Fluffy

252 HP/252 Atk/4 Sp.D

Hammer Arm
Thrash
Payback
Rock Slide

**Comment by impromptuu** [comment]
Scrafty @ Assault Vest
Ability: Intimidate
EVs: 252 HP / 164 Atk / 92 SpD
Careful Nature
- Fake Out
- Drain Punch
- Knock Off
- Ice Punch

**Comment by impromptuu** [comment]
Hawlucha @ Sitrus Berry
Ability: Unburden
EVs: 12 HP / 244 Atk / 252 Spe
Jolly Nature
- Substitute
- Swords Dance
- Acrobatics
- High Jump Kick

**Comment by impromptuu** [comment]
Hariyama @ Sitrus Berry
Ability: Guts
EVs: 28 HP / 172 Atk / 132 Def / 172 SpD
Brave Nature
0 Spe IV
- Fake Out
- Close Combat
- Knock Off
- Wide Guard

**Comment by Daviduxtor** [comment]
Conkeldurr (M) @ Assault Vest
Ability: Guts
EVs: 252 Atk / 8 Def / 248 SDef
Adamant Nature
- Knock Off
- Drain Punch
- Mach Punch
- Ice Punch

**Comment by Daviduxtor** [comment]
Don't add more cause then he will die creating all of this pokemons.

**Comment by Daviduxtor** [comment]
@gr33nd3v1l if u want add the tipics like lukario and blaziken but I put this to not repeat all the time the most popular pokemon

**Comment by EsmeeInWonderland** [comment]
I'd love the exact same Lucario you made for someone once (and send me a copy) but this time with Bullet Punch :D (it was non-shiny) but I can also just continue my breeding if there's no popular demand. Nice suggestions David.

**Comment by gr33nd3v1l** [comment]
Good job David!

**Comment by Miisha** [comment]
Would also like lucario :)

Throw in Mienshao from the TODO list to get two birds in one stone ^^

**Comment by gr33nd3v1l** [comment]
@EsmeeInWonderland that Lucario had BP on relearn, and today's has it too
